const HOTELS_REQUEST = 'HOTELS_REQUEST';
const HOTELS_REQUEST_FETCH = 'HOTELS_REQUEST_FETCH';
const HOTELS_SUCCESS = 'HOTELS_SUCCESS';
const HOTELS_FAIL = 'HOTELS_FAIL';

export { HOTELS_REQUEST, HOTELS_SUCCESS, HOTELS_FAIL, HOTELS_REQUEST_FETCH };
