const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
const INITIALIZE_FAVOURITE = 'INITIALIZE_FAVOURITE';

export { ADD_TO_FAVOURITE, REMOVE_FROM_FAVOURITE, INITIALIZE_FAVOURITE };
